#!/bin/bash

###############################################################################
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#
###############################################################################

script_name=$(basename "$0")
script_dir="$( cd "$(dirname "$0")" ; pwd -P )"

source "${script_dir}/fc-common"

###############################################################################
# Default options
set -e # stop on error

###############################################################################
# Usage
usage() {
    echo "usage: ${script_name} [OPTS]"
    echo "OPTS:"
    echo "    -p | --language              Language to make pretty (bash)"
    echo "    -l | --lic                   Display license"
    echo "    -h | --help                  Display this help message"
    exit 0
}

###############################################################################
# Parse cli args
if [ $# -eq 0 ]; then
    usage
fi

while [[ $# -gt 0 ]]; do
    case "$1" in
        -p|--language) cli_language=$2; shift ;;
        -l|--lic) fc_legal -n "${script_name}" -d "${script_dir}" ;;
        -h*|--help*|*) usage ;;
    esac
    shift # arg parsed, move to next one
done

###############################################################################
# Check bash scripts
fc_pretty_bash() {
    # find . -name "*.sh" -print0 | xargs -0 shellcheck
    find . -name "fc-*" -print0 | xargs -0 shellcheck
}

###############################################################################
# Script execution start
if [ "${cli_language}" = "bash" ]; then
    fc_pretty_bash
fi
